// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SearchRankChecker.Api.Infrastructure.Persistence;

#nullable disable

namespace SearchRankChecker.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241130150950_CascadeDeleteSearchResult")]
    partial class CascadeDeleteSearchResult
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SearchRankChecker.Api.Entities.SearchHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("SearchDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SearchEngine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SearchTerm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SearchHistory", (string)null);
                });

            modelBuilder.Entity("SearchRankChecker.Api.Entities.SearchResultEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("SearchHistoryId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SearchHistoryId");

                    b.ToTable("SearchResultEntry", (string)null);
                });

            modelBuilder.Entity("SearchRankChecker.Api.Entities.SearchResultEntry", b =>
                {
                    b.HasOne("SearchRankChecker.Api.Entities.SearchHistory", "SearchHistory")
                        .WithMany("SearchResultEntries")
                        .HasForeignKey("SearchHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SearchResultEntry_SearchHistory");

                    b.Navigation("SearchHistory");
                });

            modelBuilder.Entity("SearchRankChecker.Api.Entities.SearchHistory", b =>
                {
                    b.Navigation("SearchResultEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
